# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable, Optional
from typing_extensions import Literal

import httpx

from ..types import extract_create_params
from .._types import Body, Omit, Query, Headers, NotGiven, SequenceNotStr, omit, not_given
from .._utils import maybe_transform, async_maybe_transform
from .._compat import cached_property
from .._resource import SyncAPIResource, AsyncAPIResource
from .._response import (
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
)
from .._base_client import make_request_options
from ..types.extract_create_response import ExtractCreateResponse

__all__ = ["ExtractResource", "AsyncExtractResource"]


class ExtractResource(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ExtractResourceWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/stainless-sdks/nimbleway-python#accessing-raw-response-data-eg-headers
        """
        return ExtractResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> ExtractResourceWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/stainless-sdks/nimbleway-python#with_streaming_response
        """
        return ExtractResourceWithStreamingResponse(self)

    def create(
        self,
        *,
        url: str,
        aggregate: Literal["csv", "ndjson", "json"] | Omit = omit,
        async_timeout: float | Omit = omit,
        base_domain: str | Omit = omit,
        batch_callback_url: str | Omit = omit,
        browser: Literal["chrome", "firefox"] | Omit = omit,
        browser_version: str | Omit = omit,
        callback_url: Optional[str] | Omit = omit,
        city: str | Omit = omit,
        client_timeout: float | Omit = omit,
        consent_header: Union[Literal["true", "false"], bool] | Omit = omit,
        cookies: Union[Iterable[extract_create_params.CookiesUnionMember0], str] | Omit = omit,
        country: Literal[
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CU",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "EH",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IO",
            "IQ",
            "IR",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KP",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SD",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SY",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW",
            "ALL",
        ]
        | Omit = omit,
        debug_options: extract_create_params.DebugOptions | Omit = omit,
        device: Literal["desktop", "mobile", "tablet"] | Omit = omit,
        disable_ip_check: Union[Literal["true", "false"], bool] | Omit = omit,
        driver: Literal["vx6", "vx8", "vx8-pro", "vx10", "vx10-pro", "vx12", "vx12-pro"] | Omit = omit,
        dynamic_parser: Dict[str, Optional[object]] | Omit = omit,
        expected_status_codes: Iterable[int] | Omit = omit,
        export_userbrowser: Union[Literal["true", "false"], bool] | Omit = omit,
        format: Literal["json", "html", "csv", "raw", "json-lines", "markdown"] | Omit = omit,
        headers: Dict[str, Union[str, SequenceNotStr[str], None]] | Omit = omit,
        headless: Union[Literal["true", "false"], bool] | Omit = omit,
        http2: Union[Literal["true", "false"], bool] | Omit = omit,
        ip6: Union[Literal["true", "false"], bool] | Omit = omit,
        is_xhr: Union[Literal["true", "false"], bool] | Omit = omit,
        locale: Literal[
            "aa-DJ",
            "aa-ER",
            "aa-ET",
            "af",
            "af-NA",
            "af-ZA",
            "ak",
            "ak-GH",
            "am",
            "am-ET",
            "an-ES",
            "ar",
            "ar-AE",
            "ar-BH",
            "ar-DZ",
            "ar-EG",
            "ar-IN",
            "ar-IQ",
            "ar-JO",
            "ar-KW",
            "ar-LB",
            "ar-LY",
            "ar-MA",
            "ar-OM",
            "ar-QA",
            "ar-SA",
            "ar-SD",
            "ar-SY",
            "ar-TN",
            "ar-YE",
            "as",
            "as-IN",
            "asa",
            "asa-TZ",
            "ast-ES",
            "az",
            "az-AZ",
            "az-Cyrl",
            "az-Cyrl-AZ",
            "az-Latn",
            "az-Latn-AZ",
            "be",
            "be-BY",
            "bem",
            "bem-ZM",
            "ber-DZ",
            "ber-MA",
            "bez",
            "bez-TZ",
            "bg",
            "bg-BG",
            "bho-IN",
            "bm",
            "bm-ML",
            "bn",
            "bn-BD",
            "bn-IN",
            "bo",
            "bo-CN",
            "bo-IN",
            "br-FR",
            "brx-IN",
            "bs",
            "bs-BA",
            "byn-ER",
            "ca",
            "ca-AD",
            "ca-ES",
            "ca-FR",
            "ca-IT",
            "cgg",
            "cgg-UG",
            "chr",
            "chr-US",
            "crh-UA",
            "cs",
            "cs-CZ",
            "csb-PL",
            "cv-RU",
            "cy",
            "cy-GB",
            "da",
            "da-DK",
            "dav",
            "dav-KE",
            "de",
            "de-AT",
            "de-BE",
            "de-CH",
            "de-DE",
            "de-LI",
            "de-LU",
            "dv-MV",
            "dz-BT",
            "ebu",
            "ebu-KE",
            "ee",
            "ee-GH",
            "ee-TG",
            "el",
            "el-CY",
            "el-GR",
            "en",
            "en-AG",
            "en-AS",
            "en-AU",
            "en-BE",
            "en-BW",
            "en-BZ",
            "en-CA",
            "en-DK",
            "en-GB",
            "en-GU",
            "en-HK",
            "en-IE",
            "en-IN",
            "en-JM",
            "en-MH",
            "en-MP",
            "en-MT",
            "en-MU",
            "en-NA",
            "en-NG",
            "en-NZ",
            "en-PH",
            "en-PK",
            "en-SG",
            "en-TT",
            "en-UM",
            "en-US",
            "en-VI",
            "en-ZA",
            "en-ZM",
            "en-ZW",
            "eo",
            "es",
            "es-419",
            "es-AR",
            "es-BO",
            "es-CL",
            "es-CO",
            "es-CR",
            "es-CU",
            "es-DO",
            "es-EC",
            "es-ES",
            "es-GQ",
            "es-GT",
            "es-HN",
            "es-MX",
            "es-NI",
            "es-PA",
            "es-PE",
            "es-PR",
            "es-PY",
            "es-SV",
            "es-US",
            "es-UY",
            "es-VE",
            "et",
            "et-EE",
            "eu",
            "eu-ES",
            "fa",
            "fa-AF",
            "fa-IR",
            "ff",
            "ff-SN",
            "fi",
            "fi-FI",
            "fil",
            "fil-PH",
            "fo",
            "fo-FO",
            "fr",
            "fr-BE",
            "fr-BF",
            "fr-BI",
            "fr-BJ",
            "fr-BL",
            "fr-CA",
            "fr-CD",
            "fr-CF",
            "fr-CG",
            "fr-CH",
            "fr-CI",
            "fr-CM",
            "fr-DJ",
            "fr-FR",
            "fr-GA",
            "fr-GN",
            "fr-GP",
            "fr-GQ",
            "fr-KM",
            "fr-LU",
            "fr-MC",
            "fr-MF",
            "fr-MG",
            "fr-ML",
            "fr-MQ",
            "fr-NE",
            "fr-RE",
            "fr-RW",
            "fr-SN",
            "fr-TD",
            "fr-TG",
            "fur-IT",
            "fy-DE",
            "fy-NL",
            "ga",
            "ga-IE",
            "gd-GB",
            "gez-ER",
            "gez-ET",
            "gl",
            "gl-ES",
            "gsw",
            "gsw-CH",
            "gu",
            "gu-IN",
            "guz",
            "guz-KE",
            "gv",
            "gv-GB",
            "ha",
            "ha-Latn",
            "ha-Latn-GH",
            "ha-Latn-NE",
            "ha-Latn-NG",
            "ha-NG",
            "haw",
            "haw-US",
            "he",
            "he-IL",
            "hi",
            "hi-IN",
            "hne-IN",
            "hr",
            "hr-HR",
            "hsb-DE",
            "ht-HT",
            "hu",
            "hu-HU",
            "hy",
            "hy-AM",
            "id",
            "id-ID",
            "ig",
            "ig-NG",
            "ii",
            "ii-CN",
            "ik-CA",
            "is",
            "is-IS",
            "it",
            "it-CH",
            "it-IT",
            "iu-CA",
            "iw-IL",
            "ja",
            "ja-JP",
            "jmc",
            "jmc-TZ",
            "ka",
            "ka-GE",
            "kab",
            "kab-DZ",
            "kam",
            "kam-KE",
            "kde",
            "kde-TZ",
            "kea",
            "kea-CV",
            "khq",
            "khq-ML",
            "ki",
            "ki-KE",
            "kk",
            "kk-Cyrl",
            "kk-Cyrl-KZ",
            "kk-KZ",
            "kl",
            "kl-GL",
            "kln",
            "kln-KE",
            "km",
            "km-KH",
            "kn",
            "kn-IN",
            "ko",
            "ko-KR",
            "kok",
            "kok-IN",
            "ks-IN",
            "ku-TR",
            "kw",
            "kw-GB",
            "ky-KG",
            "lag",
            "lag-TZ",
            "lb-LU",
            "lg",
            "lg-UG",
            "li-BE",
            "li-NL",
            "lij-IT",
            "lo-LA",
            "lt",
            "lt-LT",
            "luo",
            "luo-KE",
            "luy",
            "luy-KE",
            "lv",
            "lv-LV",
            "mag-IN",
            "mai-IN",
            "mas",
            "mas-KE",
            "mas-TZ",
            "mer",
            "mer-KE",
            "mfe",
            "mfe-MU",
            "mg",
            "mg-MG",
            "mhr-RU",
            "mi-NZ",
            "mk",
            "mk-MK",
            "ml",
            "ml-IN",
            "mn-MN",
            "mr",
            "mr-IN",
            "ms",
            "ms-BN",
            "ms-MY",
            "mt",
            "mt-MT",
            "my",
            "my-MM",
            "nan-TW",
            "naq",
            "naq-NA",
            "nb",
            "nb-NO",
            "nd",
            "nd-ZW",
            "nds-DE",
            "nds-NL",
            "ne",
            "ne-IN",
            "ne-NP",
            "nl",
            "nl-AW",
            "nl-BE",
            "nl-NL",
            "nn",
            "nn-NO",
            "nr-ZA",
            "nso-ZA",
            "nyn",
            "nyn-UG",
            "oc-FR",
            "om",
            "om-ET",
            "om-KE",
            "or",
            "or-IN",
            "os-RU",
            "pa",
            "pa-Arab",
            "pa-Arab-PK",
            "pa-Guru",
            "pa-Guru-IN",
            "pa-IN",
            "pa-PK",
            "pap-AN",
            "pl",
            "pl-PL",
            "ps",
            "ps-AF",
            "pt",
            "pt-BR",
            "pt-GW",
            "pt-MZ",
            "pt-PT",
            "rm",
            "rm-CH",
            "ro",
            "ro-MD",
            "ro-RO",
            "rof",
            "rof-TZ",
            "ru",
            "ru-MD",
            "ru-RU",
            "ru-UA",
            "rw",
            "rw-RW",
            "rwk",
            "rwk-TZ",
            "sa-IN",
            "saq",
            "saq-KE",
            "sc-IT",
            "sd-IN",
            "se-NO",
            "seh",
            "seh-MZ",
            "ses",
            "ses-ML",
            "sg",
            "sg-CF",
            "shi",
            "shi-Latn",
            "shi-Latn-MA",
            "shi-Tfng",
            "shi-Tfng-MA",
            "shs-CA",
            "si",
            "si-LK",
            "sid-ET",
            "sk",
            "sk-SK",
            "sl",
            "sl-SI",
            "sn",
            "sn-ZW",
            "so",
            "so-DJ",
            "so-ET",
            "so-KE",
            "so-SO",
            "sq",
            "sq-AL",
            "sq-MK",
            "sr",
            "sr-Cyrl",
            "sr-Cyrl-BA",
            "sr-Cyrl-ME",
            "sr-Cyrl-RS",
            "sr-Latn",
            "sr-Latn-BA",
            "sr-Latn-ME",
            "sr-Latn-RS",
            "sr-ME",
            "sr-RS",
            "ss-ZA",
            "st-ZA",
            "sv",
            "sv-FI",
            "sv-SE",
            "sw",
            "sw-KE",
            "sw-TZ",
            "ta",
            "ta-IN",
            "ta-LK",
            "te",
            "te-IN",
            "teo",
            "teo-KE",
            "teo-UG",
            "tg-TJ",
            "th",
            "th-TH",
            "ti",
            "ti-ER",
            "ti-ET",
            "tig-ER",
            "tk-TM",
            "tl-PH",
            "tn-ZA",
            "to",
            "to-TO",
            "tr",
            "tr-CY",
            "tr-TR",
            "ts-ZA",
            "tt-RU",
            "tzm",
            "tzm-Latn",
            "tzm-Latn-MA",
            "ug-CN",
            "uk",
            "uk-UA",
            "unm-US",
            "ur",
            "ur-IN",
            "ur-PK",
            "uz",
            "uz-Arab",
            "uz-Arab-AF",
            "uz-Cyrl",
            "uz-Cyrl-UZ",
            "uz-Latn",
            "uz-Latn-UZ",
            "uz-UZ",
            "ve-ZA",
            "vi",
            "vi-VN",
            "vun",
            "vun-TZ",
            "wa-BE",
            "wae-CH",
            "wal-ET",
            "wo-SN",
            "xh-ZA",
            "xog",
            "xog-UG",
            "yi-US",
            "yo",
            "yo-NG",
            "yue-HK",
            "zh",
            "zh-CN",
            "zh-HK",
            "zh-Hans",
            "zh-Hans-CN",
            "zh-Hans-HK",
            "zh-Hans-MO",
            "zh-Hans-SG",
            "zh-Hant",
            "zh-Hant-HK",
            "zh-Hant-MO",
            "zh-Hant-TW",
            "zh-SG",
            "zh-TW",
            "zu",
            "zu-ZA",
            "auto",
        ]
        | Omit = omit,
        markdown: Union[Literal["true", "false"], bool] | Omit = omit,
        metadata: extract_create_params.Metadata | Omit = omit,
        method: Literal["GET", "POST", "PUT", "PATCH", "DELETE"] | Omit = omit,
        native_mode: Literal["requester", "apm", "direct"] | Omit = omit,
        network_capture: Iterable[extract_create_params.NetworkCapture] | Omit = omit,
        no_html: Union[Literal["true", "false"], bool] | Omit = omit,
        no_userbrowser: Union[Literal["true", "false"], bool] | Omit = omit,
        os: Literal["windows", "mac os", "linux", "android", "ios"] | Omit = omit,
        parse: Union[Literal["true", "false"], bool] | Omit = omit,
        parse_options: extract_create_params.ParseOptions | Omit = omit,
        parser: Union[Dict[str, Optional[object]], str] | Omit = omit,
        proxy_provider: Literal[
            "brightdata",
            "oxylabs",
            "smartproxy",
            "proxit",
            "proxit_preprod",
            "local",
            "rayobyte",
            "always",
            "oculusproxies",
            "froxy",
            "packetstream",
            "911proxy",
            "direct911proxy",
            "thesocialproxy",
            "thesocialproxy2",
            "nimble-isp",
            "nimble-isp-mobile",
            "proxit-linux",
            "proxit-macos",
            "proxit-windows",
            "proxit-rental",
            "ipfoxy",
            "brightup",
        ]
        | Omit = omit,
        proxy_providers: extract_create_params.ProxyProviders | Omit = omit,
        query_template: extract_create_params.QueryTemplate | Omit = omit,
        raw_headers: Union[Literal["true", "false"], bool] | Omit = omit,
        referrer_type: Literal[
            "random", "no-referer", "same-origin", "google", "bing", "facebook", "twitter", "instagram"
        ]
        | Omit = omit,
        render: Union[Literal["true", "false"], bool] | Omit = omit,
        render_flow: Iterable[object] | Omit = omit,
        render_options: extract_create_params.RenderOptions | Omit = omit,
        requests: Iterable[Optional[object]] | Omit = omit,
        return_response_headers_as_header: Union[Literal["true", "false"], bool] | Omit = omit,
        save_userbrowser: Union[Literal["true", "false"], bool] | Omit = omit,
        session_id: str | Omit = omit,
        session_prefetch_userbrowser: bool | Omit = omit,
        session_retry: bool | Omit = omit,
        session_timeout: float | Omit = omit,
        skill: Union[str, SequenceNotStr[str]] | Omit = omit,
        skip_ubct: bool | Omit = omit,
        state: Literal[
            "AL",
            "AK",
            "AS",
            "AZ",
            "AR",
            "CA",
            "CO",
            "CT",
            "DE",
            "DC",
            "FL",
            "GA",
            "GU",
            "HI",
            "ID",
            "IL",
            "IN",
            "IA",
            "KS",
            "KY",
            "LA",
            "ME",
            "MD",
            "MA",
            "MI",
            "MN",
            "MS",
            "MO",
            "MT",
            "NE",
            "NV",
            "NH",
            "NJ",
            "NM",
            "NY",
            "NC",
            "ND",
            "MP",
            "OH",
            "OK",
            "OR",
            "PA",
            "PR",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VT",
            "VA",
            "VI",
            "WA",
            "WV",
            "WI",
            "WY",
        ]
        | Omit = omit,
        storage_compress: Union[Literal["true", "false"], bool] | Omit = omit,
        storage_object_name: Optional[str] | Omit = omit,
        storage_type: Optional[str] | Omit = omit,
        storage_url: Optional[str] | Omit = omit,
        tag: str | Omit = omit,
        template: extract_create_params.Template | Omit = omit,
        api_timeout: float | Omit = omit,
        transform: object | Omit = omit,
        type: str | Omit = omit,
        user_context: Optional[str] | Omit = omit,
        userbrowser_creation_template_rendered: extract_create_params.UserbrowserCreationTemplateRendered | Omit = omit,
        with_proxy_usage: Union[Literal["true", "false"], bool] | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ExtractCreateResponse:
        """
        Webit v2 Realtime Web Endpoint

        Args:
          url: Target URL to scrape

          aggregate: Format for aggregating multiple batch responses

          async_timeout: Maximum time in milliseconds for async operation to complete

          base_domain: Base domain to use instead of extracting from URL

          batch_callback_url: URL to call back when the entire batch completes

          browser: Browser type to emulate

          browser_version: Specific browser version to emulate

          callback_url: URL to call back when async operation completes

          city: City for geolocation

          client_timeout: Client-side timeout in milliseconds

          consent_header: Whether to automatically handle cookie consent headers

          cookies: Browser cookies as array of cookie objects

          country: Country code for geolocation and proxy selection

          debug_options: Debug and troubleshooting options for the request

          device: Device type for browser emulation

          disable_ip_check: Whether to disable IP address validation

          driver: Browser driver to use

          dynamic_parser: Custom parser configuration as a key-value map

          expected_status_codes: Expected HTTP status codes for successful requests

          export_userbrowser: Whether to export the userbrowser session

          format: Response format

          headers: Custom HTTP headers to include in the request

          headless: Whether to run browser in headless mode

          http2: Whether to use HTTP/2 protocol

          ip6: Whether to use IPv6 for the request

          is_xhr: Whether to emulate XMLHttpRequest behavior

          locale: Locale for browser language and region settings

          markdown: Whether to return response in Markdown format

          metadata: Structured metadata about the request execution context

          method: HTTP method for the request

          native_mode: Native execution mode

          network_capture: Filters for capturing network traffic

          no_html: Whether to exclude HTML from the response

          no_userbrowser: Whether to disable browser-based rendering

          os: Operating system to emulate

          parse: Whether to parse the response content

          parse_options: Configuration options for parsing behavior

          parser: Custom parser configuration as a key-value map

          proxy_provider: Proxy provider to use for the request

          proxy_providers: Weighted distribution of proxy providers

          query_template: Query template configuration for structured data extraction

          raw_headers: Whether to return raw HTTP headers in response

          referrer_type: Referrer policy for the request

          render: Whether to render JavaScript content using a browser

          render_flow: Array of actions to perform during browser rendering

          requests: Array of request objects to process in batch

          return_response_headers_as_header: Whether to return response headers in HTTP headers

          save_userbrowser: Whether to save the userbrowser session for reuse

          skill: Skills or capabilities required for the request

          skip_ubct: Whether to skip userbrowser creation template processing

          state: US state for geolocation (only valid when country is US)

          storage_compress: Whether to compress stored data

          storage_object_name: Custom name for the stored object

          storage_type: Type of storage to use for results

          storage_url: URL for storage location

          tag: User-defined tag for request identification

          template: Userbrowser creation template configuration

          api_timeout: Request timeout in milliseconds

          transform: Transformation rules to apply to the response

          type: Type of query or scraping template

          user_context: Custom user context data to be included in the callback response

          userbrowser_creation_template_rendered: Pre-rendered userbrowser creation template configuration

          with_proxy_usage: Include proxy usage information in the response

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        return self._post(
            "/v1/extract",
            body=maybe_transform(
                {
                    "url": url,
                    "aggregate": aggregate,
                    "async_timeout": async_timeout,
                    "base_domain": base_domain,
                    "batch_callback_url": batch_callback_url,
                    "browser": browser,
                    "browser_version": browser_version,
                    "callback_url": callback_url,
                    "city": city,
                    "client_timeout": client_timeout,
                    "consent_header": consent_header,
                    "cookies": cookies,
                    "country": country,
                    "debug_options": debug_options,
                    "device": device,
                    "disable_ip_check": disable_ip_check,
                    "driver": driver,
                    "dynamic_parser": dynamic_parser,
                    "expected_status_codes": expected_status_codes,
                    "export_userbrowser": export_userbrowser,
                    "format": format,
                    "headers": headers,
                    "headless": headless,
                    "http2": http2,
                    "ip6": ip6,
                    "is_xhr": is_xhr,
                    "locale": locale,
                    "markdown": markdown,
                    "metadata": metadata,
                    "method": method,
                    "native_mode": native_mode,
                    "network_capture": network_capture,
                    "no_html": no_html,
                    "no_userbrowser": no_userbrowser,
                    "os": os,
                    "parse": parse,
                    "parse_options": parse_options,
                    "parser": parser,
                    "proxy_provider": proxy_provider,
                    "proxy_providers": proxy_providers,
                    "query_template": query_template,
                    "raw_headers": raw_headers,
                    "referrer_type": referrer_type,
                    "render": render,
                    "render_flow": render_flow,
                    "render_options": render_options,
                    "requests": requests,
                    "return_response_headers_as_header": return_response_headers_as_header,
                    "save_userbrowser": save_userbrowser,
                    "session_id": session_id,
                    "session_prefetch_userbrowser": session_prefetch_userbrowser,
                    "session_retry": session_retry,
                    "session_timeout": session_timeout,
                    "skill": skill,
                    "skip_ubct": skip_ubct,
                    "state": state,
                    "storage_compress": storage_compress,
                    "storage_object_name": storage_object_name,
                    "storage_type": storage_type,
                    "storage_url": storage_url,
                    "tag": tag,
                    "template": template,
                    "api_timeout": api_timeout,
                    "transform": transform,
                    "type": type,
                    "user_context": user_context,
                    "userbrowser_creation_template_rendered": userbrowser_creation_template_rendered,
                    "with_proxy_usage": with_proxy_usage,
                },
                extract_create_params.ExtractCreateParams,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=ExtractCreateResponse,
        )


class AsyncExtractResource(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncExtractResourceWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/stainless-sdks/nimbleway-python#accessing-raw-response-data-eg-headers
        """
        return AsyncExtractResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncExtractResourceWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/stainless-sdks/nimbleway-python#with_streaming_response
        """
        return AsyncExtractResourceWithStreamingResponse(self)

    async def create(
        self,
        *,
        url: str,
        aggregate: Literal["csv", "ndjson", "json"] | Omit = omit,
        async_timeout: float | Omit = omit,
        base_domain: str | Omit = omit,
        batch_callback_url: str | Omit = omit,
        browser: Literal["chrome", "firefox"] | Omit = omit,
        browser_version: str | Omit = omit,
        callback_url: Optional[str] | Omit = omit,
        city: str | Omit = omit,
        client_timeout: float | Omit = omit,
        consent_header: Union[Literal["true", "false"], bool] | Omit = omit,
        cookies: Union[Iterable[extract_create_params.CookiesUnionMember0], str] | Omit = omit,
        country: Literal[
            "AD",
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "AX",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BQ",
            "BR",
            "BS",
            "BT",
            "BV",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CC",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CK",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CU",
            "CV",
            "CW",
            "CX",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "EH",
            "ER",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FK",
            "FM",
            "FO",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GS",
            "GT",
            "GU",
            "GW",
            "GY",
            "HK",
            "HM",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IM",
            "IN",
            "IO",
            "IQ",
            "IR",
            "IS",
            "IT",
            "JE",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KP",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NC",
            "NE",
            "NF",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NU",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PF",
            "PG",
            "PH",
            "PK",
            "PL",
            "PM",
            "PN",
            "PR",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SD",
            "SE",
            "SG",
            "SH",
            "SI",
            "SJ",
            "SK",
            "SL",
            "SM",
            "SN",
            "SO",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SY",
            "SZ",
            "TC",
            "TD",
            "TF",
            "TG",
            "TH",
            "TJ",
            "TK",
            "TL",
            "TM",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UM",
            "US",
            "UY",
            "UZ",
            "VA",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WF",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW",
            "ALL",
        ]
        | Omit = omit,
        debug_options: extract_create_params.DebugOptions | Omit = omit,
        device: Literal["desktop", "mobile", "tablet"] | Omit = omit,
        disable_ip_check: Union[Literal["true", "false"], bool] | Omit = omit,
        driver: Literal["vx6", "vx8", "vx8-pro", "vx10", "vx10-pro", "vx12", "vx12-pro"] | Omit = omit,
        dynamic_parser: Dict[str, Optional[object]] | Omit = omit,
        expected_status_codes: Iterable[int] | Omit = omit,
        export_userbrowser: Union[Literal["true", "false"], bool] | Omit = omit,
        format: Literal["json", "html", "csv", "raw", "json-lines", "markdown"] | Omit = omit,
        headers: Dict[str, Union[str, SequenceNotStr[str], None]] | Omit = omit,
        headless: Union[Literal["true", "false"], bool] | Omit = omit,
        http2: Union[Literal["true", "false"], bool] | Omit = omit,
        ip6: Union[Literal["true", "false"], bool] | Omit = omit,
        is_xhr: Union[Literal["true", "false"], bool] | Omit = omit,
        locale: Literal[
            "aa-DJ",
            "aa-ER",
            "aa-ET",
            "af",
            "af-NA",
            "af-ZA",
            "ak",
            "ak-GH",
            "am",
            "am-ET",
            "an-ES",
            "ar",
            "ar-AE",
            "ar-BH",
            "ar-DZ",
            "ar-EG",
            "ar-IN",
            "ar-IQ",
            "ar-JO",
            "ar-KW",
            "ar-LB",
            "ar-LY",
            "ar-MA",
            "ar-OM",
            "ar-QA",
            "ar-SA",
            "ar-SD",
            "ar-SY",
            "ar-TN",
            "ar-YE",
            "as",
            "as-IN",
            "asa",
            "asa-TZ",
            "ast-ES",
            "az",
            "az-AZ",
            "az-Cyrl",
            "az-Cyrl-AZ",
            "az-Latn",
            "az-Latn-AZ",
            "be",
            "be-BY",
            "bem",
            "bem-ZM",
            "ber-DZ",
            "ber-MA",
            "bez",
            "bez-TZ",
            "bg",
            "bg-BG",
            "bho-IN",
            "bm",
            "bm-ML",
            "bn",
            "bn-BD",
            "bn-IN",
            "bo",
            "bo-CN",
            "bo-IN",
            "br-FR",
            "brx-IN",
            "bs",
            "bs-BA",
            "byn-ER",
            "ca",
            "ca-AD",
            "ca-ES",
            "ca-FR",
            "ca-IT",
            "cgg",
            "cgg-UG",
            "chr",
            "chr-US",
            "crh-UA",
            "cs",
            "cs-CZ",
            "csb-PL",
            "cv-RU",
            "cy",
            "cy-GB",
            "da",
            "da-DK",
            "dav",
            "dav-KE",
            "de",
            "de-AT",
            "de-BE",
            "de-CH",
            "de-DE",
            "de-LI",
            "de-LU",
            "dv-MV",
            "dz-BT",
            "ebu",
            "ebu-KE",
            "ee",
            "ee-GH",
            "ee-TG",
            "el",
            "el-CY",
            "el-GR",
            "en",
            "en-AG",
            "en-AS",
            "en-AU",
            "en-BE",
            "en-BW",
            "en-BZ",
            "en-CA",
            "en-DK",
            "en-GB",
            "en-GU",
            "en-HK",
            "en-IE",
            "en-IN",
            "en-JM",
            "en-MH",
            "en-MP",
            "en-MT",
            "en-MU",
            "en-NA",
            "en-NG",
            "en-NZ",
            "en-PH",
            "en-PK",
            "en-SG",
            "en-TT",
            "en-UM",
            "en-US",
            "en-VI",
            "en-ZA",
            "en-ZM",
            "en-ZW",
            "eo",
            "es",
            "es-419",
            "es-AR",
            "es-BO",
            "es-CL",
            "es-CO",
            "es-CR",
            "es-CU",
            "es-DO",
            "es-EC",
            "es-ES",
            "es-GQ",
            "es-GT",
            "es-HN",
            "es-MX",
            "es-NI",
            "es-PA",
            "es-PE",
            "es-PR",
            "es-PY",
            "es-SV",
            "es-US",
            "es-UY",
            "es-VE",
            "et",
            "et-EE",
            "eu",
            "eu-ES",
            "fa",
            "fa-AF",
            "fa-IR",
            "ff",
            "ff-SN",
            "fi",
            "fi-FI",
            "fil",
            "fil-PH",
            "fo",
            "fo-FO",
            "fr",
            "fr-BE",
            "fr-BF",
            "fr-BI",
            "fr-BJ",
            "fr-BL",
            "fr-CA",
            "fr-CD",
            "fr-CF",
            "fr-CG",
            "fr-CH",
            "fr-CI",
            "fr-CM",
            "fr-DJ",
            "fr-FR",
            "fr-GA",
            "fr-GN",
            "fr-GP",
            "fr-GQ",
            "fr-KM",
            "fr-LU",
            "fr-MC",
            "fr-MF",
            "fr-MG",
            "fr-ML",
            "fr-MQ",
            "fr-NE",
            "fr-RE",
            "fr-RW",
            "fr-SN",
            "fr-TD",
            "fr-TG",
            "fur-IT",
            "fy-DE",
            "fy-NL",
            "ga",
            "ga-IE",
            "gd-GB",
            "gez-ER",
            "gez-ET",
            "gl",
            "gl-ES",
            "gsw",
            "gsw-CH",
            "gu",
            "gu-IN",
            "guz",
            "guz-KE",
            "gv",
            "gv-GB",
            "ha",
            "ha-Latn",
            "ha-Latn-GH",
            "ha-Latn-NE",
            "ha-Latn-NG",
            "ha-NG",
            "haw",
            "haw-US",
            "he",
            "he-IL",
            "hi",
            "hi-IN",
            "hne-IN",
            "hr",
            "hr-HR",
            "hsb-DE",
            "ht-HT",
            "hu",
            "hu-HU",
            "hy",
            "hy-AM",
            "id",
            "id-ID",
            "ig",
            "ig-NG",
            "ii",
            "ii-CN",
            "ik-CA",
            "is",
            "is-IS",
            "it",
            "it-CH",
            "it-IT",
            "iu-CA",
            "iw-IL",
            "ja",
            "ja-JP",
            "jmc",
            "jmc-TZ",
            "ka",
            "ka-GE",
            "kab",
            "kab-DZ",
            "kam",
            "kam-KE",
            "kde",
            "kde-TZ",
            "kea",
            "kea-CV",
            "khq",
            "khq-ML",
            "ki",
            "ki-KE",
            "kk",
            "kk-Cyrl",
            "kk-Cyrl-KZ",
            "kk-KZ",
            "kl",
            "kl-GL",
            "kln",
            "kln-KE",
            "km",
            "km-KH",
            "kn",
            "kn-IN",
            "ko",
            "ko-KR",
            "kok",
            "kok-IN",
            "ks-IN",
            "ku-TR",
            "kw",
            "kw-GB",
            "ky-KG",
            "lag",
            "lag-TZ",
            "lb-LU",
            "lg",
            "lg-UG",
            "li-BE",
            "li-NL",
            "lij-IT",
            "lo-LA",
            "lt",
            "lt-LT",
            "luo",
            "luo-KE",
            "luy",
            "luy-KE",
            "lv",
            "lv-LV",
            "mag-IN",
            "mai-IN",
            "mas",
            "mas-KE",
            "mas-TZ",
            "mer",
            "mer-KE",
            "mfe",
            "mfe-MU",
            "mg",
            "mg-MG",
            "mhr-RU",
            "mi-NZ",
            "mk",
            "mk-MK",
            "ml",
            "ml-IN",
            "mn-MN",
            "mr",
            "mr-IN",
            "ms",
            "ms-BN",
            "ms-MY",
            "mt",
            "mt-MT",
            "my",
            "my-MM",
            "nan-TW",
            "naq",
            "naq-NA",
            "nb",
            "nb-NO",
            "nd",
            "nd-ZW",
            "nds-DE",
            "nds-NL",
            "ne",
            "ne-IN",
            "ne-NP",
            "nl",
            "nl-AW",
            "nl-BE",
            "nl-NL",
            "nn",
            "nn-NO",
            "nr-ZA",
            "nso-ZA",
            "nyn",
            "nyn-UG",
            "oc-FR",
            "om",
            "om-ET",
            "om-KE",
            "or",
            "or-IN",
            "os-RU",
            "pa",
            "pa-Arab",
            "pa-Arab-PK",
            "pa-Guru",
            "pa-Guru-IN",
            "pa-IN",
            "pa-PK",
            "pap-AN",
            "pl",
            "pl-PL",
            "ps",
            "ps-AF",
            "pt",
            "pt-BR",
            "pt-GW",
            "pt-MZ",
            "pt-PT",
            "rm",
            "rm-CH",
            "ro",
            "ro-MD",
            "ro-RO",
            "rof",
            "rof-TZ",
            "ru",
            "ru-MD",
            "ru-RU",
            "ru-UA",
            "rw",
            "rw-RW",
            "rwk",
            "rwk-TZ",
            "sa-IN",
            "saq",
            "saq-KE",
            "sc-IT",
            "sd-IN",
            "se-NO",
            "seh",
            "seh-MZ",
            "ses",
            "ses-ML",
            "sg",
            "sg-CF",
            "shi",
            "shi-Latn",
            "shi-Latn-MA",
            "shi-Tfng",
            "shi-Tfng-MA",
            "shs-CA",
            "si",
            "si-LK",
            "sid-ET",
            "sk",
            "sk-SK",
            "sl",
            "sl-SI",
            "sn",
            "sn-ZW",
            "so",
            "so-DJ",
            "so-ET",
            "so-KE",
            "so-SO",
            "sq",
            "sq-AL",
            "sq-MK",
            "sr",
            "sr-Cyrl",
            "sr-Cyrl-BA",
            "sr-Cyrl-ME",
            "sr-Cyrl-RS",
            "sr-Latn",
            "sr-Latn-BA",
            "sr-Latn-ME",
            "sr-Latn-RS",
            "sr-ME",
            "sr-RS",
            "ss-ZA",
            "st-ZA",
            "sv",
            "sv-FI",
            "sv-SE",
            "sw",
            "sw-KE",
            "sw-TZ",
            "ta",
            "ta-IN",
            "ta-LK",
            "te",
            "te-IN",
            "teo",
            "teo-KE",
            "teo-UG",
            "tg-TJ",
            "th",
            "th-TH",
            "ti",
            "ti-ER",
            "ti-ET",
            "tig-ER",
            "tk-TM",
            "tl-PH",
            "tn-ZA",
            "to",
            "to-TO",
            "tr",
            "tr-CY",
            "tr-TR",
            "ts-ZA",
            "tt-RU",
            "tzm",
            "tzm-Latn",
            "tzm-Latn-MA",
            "ug-CN",
            "uk",
            "uk-UA",
            "unm-US",
            "ur",
            "ur-IN",
            "ur-PK",
            "uz",
            "uz-Arab",
            "uz-Arab-AF",
            "uz-Cyrl",
            "uz-Cyrl-UZ",
            "uz-Latn",
            "uz-Latn-UZ",
            "uz-UZ",
            "ve-ZA",
            "vi",
            "vi-VN",
            "vun",
            "vun-TZ",
            "wa-BE",
            "wae-CH",
            "wal-ET",
            "wo-SN",
            "xh-ZA",
            "xog",
            "xog-UG",
            "yi-US",
            "yo",
            "yo-NG",
            "yue-HK",
            "zh",
            "zh-CN",
            "zh-HK",
            "zh-Hans",
            "zh-Hans-CN",
            "zh-Hans-HK",
            "zh-Hans-MO",
            "zh-Hans-SG",
            "zh-Hant",
            "zh-Hant-HK",
            "zh-Hant-MO",
            "zh-Hant-TW",
            "zh-SG",
            "zh-TW",
            "zu",
            "zu-ZA",
            "auto",
        ]
        | Omit = omit,
        markdown: Union[Literal["true", "false"], bool] | Omit = omit,
        metadata: extract_create_params.Metadata | Omit = omit,
        method: Literal["GET", "POST", "PUT", "PATCH", "DELETE"] | Omit = omit,
        native_mode: Literal["requester", "apm", "direct"] | Omit = omit,
        network_capture: Iterable[extract_create_params.NetworkCapture] | Omit = omit,
        no_html: Union[Literal["true", "false"], bool] | Omit = omit,
        no_userbrowser: Union[Literal["true", "false"], bool] | Omit = omit,
        os: Literal["windows", "mac os", "linux", "android", "ios"] | Omit = omit,
        parse: Union[Literal["true", "false"], bool] | Omit = omit,
        parse_options: extract_create_params.ParseOptions | Omit = omit,
        parser: Union[Dict[str, Optional[object]], str] | Omit = omit,
        proxy_provider: Literal[
            "brightdata",
            "oxylabs",
            "smartproxy",
            "proxit",
            "proxit_preprod",
            "local",
            "rayobyte",
            "always",
            "oculusproxies",
            "froxy",
            "packetstream",
            "911proxy",
            "direct911proxy",
            "thesocialproxy",
            "thesocialproxy2",
            "nimble-isp",
            "nimble-isp-mobile",
            "proxit-linux",
            "proxit-macos",
            "proxit-windows",
            "proxit-rental",
            "ipfoxy",
            "brightup",
        ]
        | Omit = omit,
        proxy_providers: extract_create_params.ProxyProviders | Omit = omit,
        query_template: extract_create_params.QueryTemplate | Omit = omit,
        raw_headers: Union[Literal["true", "false"], bool] | Omit = omit,
        referrer_type: Literal[
            "random", "no-referer", "same-origin", "google", "bing", "facebook", "twitter", "instagram"
        ]
        | Omit = omit,
        render: Union[Literal["true", "false"], bool] | Omit = omit,
        render_flow: Iterable[object] | Omit = omit,
        render_options: extract_create_params.RenderOptions | Omit = omit,
        requests: Iterable[Optional[object]] | Omit = omit,
        return_response_headers_as_header: Union[Literal["true", "false"], bool] | Omit = omit,
        save_userbrowser: Union[Literal["true", "false"], bool] | Omit = omit,
        session_id: str | Omit = omit,
        session_prefetch_userbrowser: bool | Omit = omit,
        session_retry: bool | Omit = omit,
        session_timeout: float | Omit = omit,
        skill: Union[str, SequenceNotStr[str]] | Omit = omit,
        skip_ubct: bool | Omit = omit,
        state: Literal[
            "AL",
            "AK",
            "AS",
            "AZ",
            "AR",
            "CA",
            "CO",
            "CT",
            "DE",
            "DC",
            "FL",
            "GA",
            "GU",
            "HI",
            "ID",
            "IL",
            "IN",
            "IA",
            "KS",
            "KY",
            "LA",
            "ME",
            "MD",
            "MA",
            "MI",
            "MN",
            "MS",
            "MO",
            "MT",
            "NE",
            "NV",
            "NH",
            "NJ",
            "NM",
            "NY",
            "NC",
            "ND",
            "MP",
            "OH",
            "OK",
            "OR",
            "PA",
            "PR",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VT",
            "VA",
            "VI",
            "WA",
            "WV",
            "WI",
            "WY",
        ]
        | Omit = omit,
        storage_compress: Union[Literal["true", "false"], bool] | Omit = omit,
        storage_object_name: Optional[str] | Omit = omit,
        storage_type: Optional[str] | Omit = omit,
        storage_url: Optional[str] | Omit = omit,
        tag: str | Omit = omit,
        template: extract_create_params.Template | Omit = omit,
        api_timeout: float | Omit = omit,
        transform: object | Omit = omit,
        type: str | Omit = omit,
        user_context: Optional[str] | Omit = omit,
        userbrowser_creation_template_rendered: extract_create_params.UserbrowserCreationTemplateRendered | Omit = omit,
        with_proxy_usage: Union[Literal["true", "false"], bool] | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> ExtractCreateResponse:
        """
        Webit v2 Realtime Web Endpoint

        Args:
          url: Target URL to scrape

          aggregate: Format for aggregating multiple batch responses

          async_timeout: Maximum time in milliseconds for async operation to complete

          base_domain: Base domain to use instead of extracting from URL

          batch_callback_url: URL to call back when the entire batch completes

          browser: Browser type to emulate

          browser_version: Specific browser version to emulate

          callback_url: URL to call back when async operation completes

          city: City for geolocation

          client_timeout: Client-side timeout in milliseconds

          consent_header: Whether to automatically handle cookie consent headers

          cookies: Browser cookies as array of cookie objects

          country: Country code for geolocation and proxy selection

          debug_options: Debug and troubleshooting options for the request

          device: Device type for browser emulation

          disable_ip_check: Whether to disable IP address validation

          driver: Browser driver to use

          dynamic_parser: Custom parser configuration as a key-value map

          expected_status_codes: Expected HTTP status codes for successful requests

          export_userbrowser: Whether to export the userbrowser session

          format: Response format

          headers: Custom HTTP headers to include in the request

          headless: Whether to run browser in headless mode

          http2: Whether to use HTTP/2 protocol

          ip6: Whether to use IPv6 for the request

          is_xhr: Whether to emulate XMLHttpRequest behavior

          locale: Locale for browser language and region settings

          markdown: Whether to return response in Markdown format

          metadata: Structured metadata about the request execution context

          method: HTTP method for the request

          native_mode: Native execution mode

          network_capture: Filters for capturing network traffic

          no_html: Whether to exclude HTML from the response

          no_userbrowser: Whether to disable browser-based rendering

          os: Operating system to emulate

          parse: Whether to parse the response content

          parse_options: Configuration options for parsing behavior

          parser: Custom parser configuration as a key-value map

          proxy_provider: Proxy provider to use for the request

          proxy_providers: Weighted distribution of proxy providers

          query_template: Query template configuration for structured data extraction

          raw_headers: Whether to return raw HTTP headers in response

          referrer_type: Referrer policy for the request

          render: Whether to render JavaScript content using a browser

          render_flow: Array of actions to perform during browser rendering

          requests: Array of request objects to process in batch

          return_response_headers_as_header: Whether to return response headers in HTTP headers

          save_userbrowser: Whether to save the userbrowser session for reuse

          skill: Skills or capabilities required for the request

          skip_ubct: Whether to skip userbrowser creation template processing

          state: US state for geolocation (only valid when country is US)

          storage_compress: Whether to compress stored data

          storage_object_name: Custom name for the stored object

          storage_type: Type of storage to use for results

          storage_url: URL for storage location

          tag: User-defined tag for request identification

          template: Userbrowser creation template configuration

          api_timeout: Request timeout in milliseconds

          transform: Transformation rules to apply to the response

          type: Type of query or scraping template

          user_context: Custom user context data to be included in the callback response

          userbrowser_creation_template_rendered: Pre-rendered userbrowser creation template configuration

          with_proxy_usage: Include proxy usage information in the response

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        return await self._post(
            "/v1/extract",
            body=await async_maybe_transform(
                {
                    "url": url,
                    "aggregate": aggregate,
                    "async_timeout": async_timeout,
                    "base_domain": base_domain,
                    "batch_callback_url": batch_callback_url,
                    "browser": browser,
                    "browser_version": browser_version,
                    "callback_url": callback_url,
                    "city": city,
                    "client_timeout": client_timeout,
                    "consent_header": consent_header,
                    "cookies": cookies,
                    "country": country,
                    "debug_options": debug_options,
                    "device": device,
                    "disable_ip_check": disable_ip_check,
                    "driver": driver,
                    "dynamic_parser": dynamic_parser,
                    "expected_status_codes": expected_status_codes,
                    "export_userbrowser": export_userbrowser,
                    "format": format,
                    "headers": headers,
                    "headless": headless,
                    "http2": http2,
                    "ip6": ip6,
                    "is_xhr": is_xhr,
                    "locale": locale,
                    "markdown": markdown,
                    "metadata": metadata,
                    "method": method,
                    "native_mode": native_mode,
                    "network_capture": network_capture,
                    "no_html": no_html,
                    "no_userbrowser": no_userbrowser,
                    "os": os,
                    "parse": parse,
                    "parse_options": parse_options,
                    "parser": parser,
                    "proxy_provider": proxy_provider,
                    "proxy_providers": proxy_providers,
                    "query_template": query_template,
                    "raw_headers": raw_headers,
                    "referrer_type": referrer_type,
                    "render": render,
                    "render_flow": render_flow,
                    "render_options": render_options,
                    "requests": requests,
                    "return_response_headers_as_header": return_response_headers_as_header,
                    "save_userbrowser": save_userbrowser,
                    "session_id": session_id,
                    "session_prefetch_userbrowser": session_prefetch_userbrowser,
                    "session_retry": session_retry,
                    "session_timeout": session_timeout,
                    "skill": skill,
                    "skip_ubct": skip_ubct,
                    "state": state,
                    "storage_compress": storage_compress,
                    "storage_object_name": storage_object_name,
                    "storage_type": storage_type,
                    "storage_url": storage_url,
                    "tag": tag,
                    "template": template,
                    "api_timeout": api_timeout,
                    "transform": transform,
                    "type": type,
                    "user_context": user_context,
                    "userbrowser_creation_template_rendered": userbrowser_creation_template_rendered,
                    "with_proxy_usage": with_proxy_usage,
                },
                extract_create_params.ExtractCreateParams,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=ExtractCreateResponse,
        )


class ExtractResourceWithRawResponse:
    def __init__(self, extract: ExtractResource) -> None:
        self._extract = extract

        self.create = to_raw_response_wrapper(
            extract.create,
        )


class AsyncExtractResourceWithRawResponse:
    def __init__(self, extract: AsyncExtractResource) -> None:
        self._extract = extract

        self.create = async_to_raw_response_wrapper(
            extract.create,
        )


class ExtractResourceWithStreamingResponse:
    def __init__(self, extract: ExtractResource) -> None:
        self._extract = extract

        self.create = to_streamed_response_wrapper(
            extract.create,
        )


class AsyncExtractResourceWithStreamingResponse:
    def __init__(self, extract: AsyncExtractResource) -> None:
        self._extract = extract

        self.create = async_to_streamed_response_wrapper(
            extract.create,
        )
